export const PLANS = {
  starter: {
    name: { de: 'Starter', fr: 'Starter', en: 'Starter', es: 'Starter', nl: 'Starter', it: 'Starter', bs: 'Starter' },
    price_monthly: 2.99,
    price_yearly: null as number | null,
    stories_per_month: 10,
    child_profiles: 1,
    images_per_story: 2,
    all_languages: true,
    quizzes: true,
    learning_themes: false,
    chapter_stories: false,
    co_create: false,
  },
  standard: {
    name: { de: 'Standard', fr: 'Standard', en: 'Standard', es: 'Estándar', nl: 'Standaard', it: 'Standard', bs: 'Standard' },
    price_monthly: 4.99,
    price_yearly: null as number | null,
    stories_per_month: 30,
    child_profiles: 2,
    images_per_story: 3,
    all_languages: true,
    quizzes: true,
    learning_themes: true,
    chapter_stories: true,
    co_create: true,
    most_popular: true,
  },
  premium: {
    name: { de: 'Premium', fr: 'Premium', en: 'Premium', es: 'Premium', nl: 'Premium', it: 'Premium', bs: 'Premium' },
    price_monthly: 6.99,
    price_yearly: null as number | null,
    stories_per_month: 45,
    child_profiles: 3,
    images_per_story: 4,
    all_languages: true,
    quizzes: true,
    learning_themes: true,
    chapter_stories: true,
    co_create: true,
  },
} as const;

export type PlanKey = keyof typeof PLANS;
