-- =============================================================================
-- Series Feature Phase 1: Schema extensions for series continuity
-- Date: 2026-02-12
-- =============================================================================

-- 1. Episode summary (max ~100 words, LLM-generated after each episode)
ALTER TABLE stories ADD COLUMN IF NOT EXISTS
  episode_summary TEXT;

COMMENT ON COLUMN stories.episode_summary IS 
  'Short summary of the episode (~100 words), generated by LLM after story creation. Used as context for next episode.';

-- 2. Continuity state (JSONB, tracks established facts, open threads, character states)
ALTER TABLE stories ADD COLUMN IF NOT EXISTS
  continuity_state JSONB;

COMMENT ON COLUMN stories.continuity_state IS 
  'Continuity tracking for series. Structure: {established_facts[], open_threads[], character_states{}, world_rules[], signature_element{description, usage_history[]}}';

-- 3. Visual style sheet (JSONB, generated in Episode 1, reused in Episodes 2-5)
ALTER TABLE stories ADD COLUMN IF NOT EXISTS
  visual_style_sheet JSONB;

COMMENT ON COLUMN stories.visual_style_sheet IS 
  'Visual consistency for series images. Structure: {characters{name: visual_description}, world_style, recurring_visual}. Generated in Ep1, copied to Ep2-5.';

-- =============================================================================
-- Done – Phase 1.1
-- These columns are nullable and have no defaults, so existing stories are
-- unaffected. The generate-story function will populate them for new series.
-- =============================================================================
